# Site settings
title: "De Sneppers"
author: "Matt Verhaegh"
description: "Website over de vriendengroep 'De Sneppers'."
keywords: "Sneppers, vrienden, Helden, Beringe"

colophon: "De Sneppers"

baseurl: ""
url: "https://www.sneppers.nl/"


email: webmaster@sneppers.nl

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
