# Site settings
title: "De Sneppers"
author: "Matt Verhaegh"
description: "Website over de vriendengroep 'De Sneppers'. De originele versie is nog <a href=http://sneppers.verhaegh.nl/>te vinden op sneppers.verhaegh.nl</a>."
keywords: "Sneppers, vrienden, Helden, Beringe"

colophon: "De Sneppers"

baseurl: ""
url: "https://www.sneppers.nl/"


email: webmaster@sneppers.nl

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
